[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
before-all = [
  "pip install sccache"
]
# Run the package tests using `pytest`
test-command = "python {package}/tests/client_test.py"

[tool.cibuildwheel.linux]
before-all = "yum install -y gperf openssl-devel || apk add --upgrade gperf openssl-dev || apt-get install gperf libssl-dev"
